# Prabhleen Gill
# Graph Theory Spring 2024
# Filename: graph.py
# Data for program (station names and distances in miles)

nodes = ["Van Cortlandt Park-242 St",
         "168 St",
         "96 St",
         "59 St-Columbus Circle",
         "Times Sq-42 St",
         "14 St 123",
         "Chambers St",
         "Chambers St",
         "Park Place",
         "Fulton St",
         "Court St",
         "Atlantic Av-Barclays Ctr",
         "Franklin Av",
         "Flatbush Av-Brooklyn",
         "Crown Hts Utica Av",
         "Livonia Av L",
         "New Lots Av",
         "135 St",
         "Harlem St",
         "149 St-Grand Concourse",
         "E 180 St",
         "Wakefield-241 St",
         "Inwood-207 St",
         "145 St",
         "50 St",
         "7 Av BDE",
         "Lexington Av/53 St",
         "Court Sq-23 St",
         "Queens Plaza",
         "Jackson Hts-Roosevelt Av",
         "Forest Hills 71 Av",
         "Briarwood",
         "14 St ACE",
         "W 4 St Wash Sq",
         "Canal St",
         "Jay St MetroTech",
         "Hoyt Schermerhorn",
         "Broadway Junction",
         "Rockaway Blvd",
         "Ozone Park-Lefferts Blvd",
         "Far Rockaway-Mott Av",
         "Woodlawn",
         "161 St-Yankee Stadium",
         "Eastchester-Dyre Av",
         "125 St",
         "3 Av-138 St",
         "Pelham Bay Park",
         "Lexington Av/59 St",
         "Grand Central-42 St",
         "14 St-Union Sq",
         "B'way-Lafayette St",
         "Canal St JNQR",
         "Brooklyn Bridge City Hall",
         "Norwood 205 St",
         "47-50 Sts Rockefeller Ctr",
         "Lexington Av/63 St",
         "Jamaica-179 St",
         "36 St",
         "42 St Bryant Pk",
         "34 St Herald Sq",
         "14 St FM",
         "Delancey St Essex St",
         "Marcy Av",
         "Myrtle Av",
         "Myrtle Wyckoff Avs",
         "Middle Village Metropolitan Av",
         "2 Av",
         "Bergen St",
         "4 Av 9 St",
         "15 St Prospect Park",
         "Church Av FG",
         "West 8 St-NY Aquarium",
         "Grand St",
         "DeKalb Av",
         "36 St DNR",
         "New Utrecht Av",
         "7 Av BQ",
         "Prospect Park BQS",
         "Brighton Beach",
         "34 St-Hudson Yards",
         "Queensboro Plaza",
         "Astoria-Ditmars Blvd",
         "Flushing-Main St",
         "96 St Q",
         "57 St-7 Av",
         "World Trade Center",
         "South Ferry",
         "59 St NR",
         "Bay Ridge 95 St",
         "Coney Island-Stillwell Av",
         "Metropolitan Av G",
         "Canarsie-Rockaway Pwky",
         "Broad St JZ",
         "Jamaica Center-Parsons/Archer"]

connections = [("Van Cortlandt Park-242 St", "168 St", 5.2),
               ("168 St", "96 St", 3.7),
               ("96 St", "59 St-Columbus Circle", 1.9),
               ("59 St-Columbus Circle", "Times Sq-42 St", 1),
               ("Times Sq-42 St", "14 St 123", 1.4),
               ("14 St 123", "Chambers St", 1.7),
               ("Chambers St", "South Ferry", 1),
               ("Chambers St", "Park Place", 0.3),
               ("Park Place", "Fulton St", 0.2),
               ("Fulton St", "Court St", 2.9),
               ("Court St", "Atlantic Av-Barclays Ctr", 1.5),
               ("Atlantic Av-Barclays Ctr", "Franklin Av", 1.2),
               ("Franklin Av", "Flatbush Av-Brooklyn", 2.7),
               ("Franklin Av", "Crown Hts Utica Av", 1.9),
               ("Crown Hts Utica Av", "Livonia Av L", 2.1),
               ("Livonia Av L", "New Lots Av", 0.7),
               ("96 St", "135 St", 2.2),
               ("135 St", "Harlem St", 1),
               ("135 St", "149 St-Grand Concourse", 1.5),
               ("149 St-Grand Concourse", "E 180 St", 3.6),
               ("E 180 St", "Wakefield-241 St", 4.7),
               ("Inwood-207 St", "168 St", 2.3),
               ("168 St", "145 St", 1.2),
               ("145 St", "59 St-Columbus Circle", 4.5),
               ("59 St-Columbus Circle", "50 St", 0.8),
               ("50 St", "7 Av BDE", 0.7),
               ("7 Av BDE", "Lexington Av/53 St", 1),
               ("Lexington Av/53 St", "Court Sq-23 St", 2.3),
               ("Court Sq-23 St", "Queens Plaza", 0.5),
               ("Queens Plaza", "Jackson Hts-Roosevelt Av", 2.5),
               ("Jackson Hts-Roosevelt Av", "Forest Hills 71 Av", 3),
               ("Forest Hills 71 Av", "Briarwood", 1.6),
               ("Briarwood", "Jamaica Center-Parsons/Archer", 1.2),
               ("50 St", "14 St ACE", 1.9),
               ("14 St ACE", "W 4 St Wash Sq", 0.6),
               ("W 4 St Wash Sq", "Canal St", 0.9),
               ("Canal St", "World Trade Center", 0.9),
               ("Canal St", "Park Place", 0.7),
               ("Park Place", "Fulton St", 0.2),
               ("Fulton St", "Jay St MetroTech", 2.2),
               ("Jay St MetroTech", "Hoyt Schermerhorn", 0.3),
               ("Hoyt Schermerhorn", "Broadway Junction", 4.6),
               ("Broadway Junction", "Rockaway Blvd", 5.4),
               ("Rockaway Blvd", "Ozone Park-Lefferts Blvd", 1.7),
               ("Rockaway Blvd", "Far Rockaway-Mott Av", 7.3),
               ("Woodlawn", "161 St-Yankee Stadium", 5.3),
               ("161 St-Yankee Stadium", "149 St-Grand Concourse", 0.7),
               ("149 St-Grand Concourse", "E 180 St", 3.6),
               ("E 180 St", "Eastchester-Dyre Av", 4.3),
               ("149 St-Grand Concourse", "125 St", 1.4),
               ("125 St", "3 Av-138 St", 0.8),
               ("3 Av-138 St", "Pelham Bay Park", 8.6),
               ("125 St", "Lexington Av/59 St", 3.3),
               ("Lexington Av/59 St", "Lexington Av/63 St", 0.2),
               ("Lexington Av/59 St", "Lexington Av/53 St", 0.5),
               ("Lexington Av/53 St", "Grand Central-42 St", 0.5),
               ("Grand Central-42 St", "14 St-Union Sq", 1.4),
               ("14 St-Union Sq", "B'way-Lafayette St", 0.7),
               ("B'way-Lafayette St", "Canal St JNQR", 0.5),
               ("Canal St JNQR", "Brooklyn Bridge City Hall", 0.4),
               ("Brooklyn Bridge City Hall", "Fulton St", 0.3),
               ("Fulton St", "Court St", 2.9),
               ("Court St", "Atlantic Av-Barclays Ctr", 1.5),
               ("Atlantic Av-Barclays Ctr", "Franklin Av", 1.3),
               ("Franklin Av", "Flatbush Av-Brooklyn", 3.5),
               ("Franklin Av", "Crown Hts Utica Av", 1.9),
               ("Norwood 205 St", "161 St-Yankee Stadium", 4.3),
               ("161 St-Yankee Stadium", "145 St", 1.3),
               ("145 St", "59 St-Columbus Circle", 4.5),
               ("59 St-Columbus Circle", "7 Av BDE", 0.3),
               ("7 Av BDE", "47-50 Sts Rockefeller Ctr", 0.4),
               ("47-50 Sts Rockefeller Ctr", "Lexington Av/63 St", 1.1),
               ("Lexington Av/63 St", "Lexington Av/59 St", 0.2),
               ("Lexington Av/63 St", "Jackson Hts-Roosevelt Av", 4.4),
               ("Jackson Hts-Roosevelt Av", "Forest Hills 71 Av", 3),
               ("Forest Hills 71 Av", "Briarwood", 1.6),
               ("Briarwood", "Jamaica-179 St", 2),
               ("47-50 Sts Rockefeller Ctr", "Lexington Av/53 St", 0.5),
               ("Lexington Av/53 St", "Court Sq-23 St", 2.3),
               ("Court Sq-23 St", "Queens Plaza", 0.5),
               ("Queens Plaza", "36 St", 1.2),
               ("36 St", "Jackson Hts-Roosevelt Av", 1.8),
               ("Jackson Hts-Roosevelt Av", "Forest Hills 71 Av", 3),
               ("47-50 Sts Rockefeller Ctr", "42 St Bryant Pk", 0.2),
               ("42 St Bryant Pk", "34 St Herald Sq", 0.2),
               ("34 St Herald Sq", "14 St FM", 1.1),
               ("14 St FM", "14 St 123", 0.1),
               ("14 St FM", "W 4 St Wash Sq", 0.3),
               ("W 4 St Wash Sq", "B'way-Lafayette St", 0.6),
               ("B'way-Lafayette St", "Delancey St Essex St", 0.8),
               ("Delancey St Essex St", "Marcy Av", 1.7),
               ("Marcy Av", "Myrtle Av", 1.8),
               ("Myrtle Av", "Myrtle Wyckoff Avs", 1.2),
               ("Myrtle Wyckoff Avs", "Middle Village Metropolitan Av", 1.9),
               ("B'way-Lafayette St", "2 Av", 0.4),
               ("2 Av", "Delancey St Essex St", 0.4),
               ("Delancey St Essex St", "Jay St MetroTech", 2.4),
               ("Jay St MetroTech", "Bergen St", 0.4),
               ("Bergen St", "4 Av 9 St", 0.5),
               ("4 Av 9 St", "15 St Prospect Park", 0.7),
               ("15 St Prospect Park", "Church Av FG", 1.1),
               ("Church Av FG", "West 8 St-NY Aquarium", 4.7),
               ("West 8 St-NY Aquarium", "Coney Island-Stillwell Av", 0.3),
               ("B'way-Lafayette St", "Grand St", 0.6),
               ("Grand St", "DeKalb Av", 2.4),
               ("DeKalb Av", "Atlantic Av-Barclays Ctr", 0.4),
               ("Atlantic Av-Barclays Ctr", "4 Av 9 St", 1.1),
               ("4 Av 9 St", "36 St DNR", 1.8),
               ("36 St DNR", "New Utrecht Av", 1.9),
               ("New Utrecht Av", "Coney Island-Stillwell Av", 3.7),
               ("Atlantic Av-Barclays Ctr", "7 Av BQ", 0.5),
               ("7 Av BQ", "Prospect Park BQS", 0.8),
               ("Prospect Park BQS", "Brighton Beach", 7),
               ("34 St-Hudson Yards", "Times Sq-42 St", 0.9),
               ("Times Sq-42 St", "42 St Bryant Pk", 0.1),
               ("42 St Bryant Pk", "Grand Central-42 St", 0.1),
               ("Grand Central-42 St", "Court Sq-23 St", 2.4),
               ("Court Sq-23 St", "Queensboro Plaza", 0.4),
               ("Queensboro Plaza", "Jackson Hts-Roosevelt Av", 2.7),
               ("Jackson Hts-Roosevelt Av", "Flushing-Main St", 3.3),
               ("96 St Q", "Lexington Av/63 St", 2.6),
               ("Lexington Av/63 St", "Lexington Av/59 St", 0.2),
               ("Lexington Av/63 St", "57 St-7 Av", 0.9),
               ("57 St-7 Av", "Lexington Av/59 St", 0.7),
               ("Lexington Av/59 St", "Queensboro Plaza", 1.6),
               ("Queensboro Plaza", "Astoria-Ditmars Blvd", 2.4),
               ("Lexington Av/59 St", "Queens Plaza", 1.8),
               ("Queens Plaza", "36 St", 1.2),
               ("36 St", "Jackson Hts-Roosevelt Av", 1.8),
               ("Jackson Hts-Roosevelt Av", "Forest Hills 71 Av", 3),
               ("57 St-7 Av", "Times Sq-42 St", 0.7),
               ("Times Sq-42 St", "34 St Herald Sq", 0.3),
               ("34 St Herald Sq", "14 St-Union Sq", 0.9),
               ("14 St-Union Sq", "Canal St JNQR", 1.3),
               ("Canal St JNQR", "DeKalb Av", 2.3),
               ("DeKalb Av", "Atlantic Av-Barclays Ctr", 0.4),
               ("Atlantic Av-Barclays Ctr", "7 Av BQ", 0.5),
               ("7 Av BQ", "Prospect Park BQS", 0.8),
               ("Prospect Park BQS", "Brighton Beach", 7),
               ("Brighton Beach", "Coney Island-Stillwell Av", 1.4),
               ("Canal St JNQR", "World Trade Center", 1),
               ("World Trade Center", "South Ferry", 0.8),
               ("South Ferry", "Court St", 1.8),
               ("Court St", "DeKalb Av", 0.7),
               ("DeKalb Av", "Atlantic Av-Barclays Ctr", 0.4),
               ("Atlantic Av-Barclays Ctr", "4 Av 9 St", 1.1),
               ("4 Av 9 St", "36 St DNR", 1.8),
               ("36 St DNR", "59 St NR", 1.1),
               ("59 St NR", "Bay Ridge 95 St", 1.7),
               ("59 St NR", "New Utrecht Av", 1.6),
               ("New Utrecht Av", "Coney Island-Stillwell Av", 3.7),
               ("Court Sq-23 St", "Metropolitan Av G", 2.6),
               ("Metropolitan Av G", "Hoyt Schermerhorn", 3),
               ("Hoyt Schermerhorn", "4 Av 9 St", 1.7),
               ("4 Av 9 St", "15 St Prospect Park", 0.7),
               ("15 St Prospect Park", "Church Av FG", 1.1),
               ("14 St ACE", "14 St 123", 0.2),
               ("14 St 123", "14 St FM", 0.2),
               ("14 St FM", "14 St-Union Sq", 0.4),
               ("14 St-Union Sq", "Metropolitan Av G", 3.5),
               ("Metropolitan Av G", "Myrtle Wyckoff Avs", 2.6),
               ("Myrtle Wyckoff Avs", "Broadway Junction", 2),
               ("Broadway Junction", "Livonia Av L", 1.2),
               ("Livonia Av L", "Canarsie-Rockaway Pwky", 1.5),
               ("Broad St JZ", "Fulton St", 0.2),
               ("Fulton St", "Brooklyn Bridge City Hall", 0.3),
               ("Brooklyn Bridge City Hall", "Canal St JNQR", 0.4),
               ("Canal St JNQR", "Delancey St Essex St", 0.8),
               ("Delancey St Essex St", "Marcy Av", 1.7),
               ("Marcy Av", "Myrtle Av", 1.8),
               ("Myrtle Av", "Broadway Junction", 2),
               ("Broadway Junction", "Jamaica Center-Parsons/Archer", 5.9)]

init_graph = {node: {} for node in nodes}

for source, target, distance in connections:
    init_graph[source][target] = distance